name = "exiftool-web"
compatibility_date = "2026-01-10"
main = ".svelte-kit/cloudflare/_worker.js"

routes = [
  { pattern = "exiftool.lucasgelfond.online", custom_domain = true }
]

[assets]
directory = ".svelte-kit/cloudflare"
